Remove done button
DigitalMasterpieces/wishkit-ios pull request #1
Opened 2023-09-12 12:40 UTC by ulibath

2023-09-13 08:50 UTC, maikz requested changes
It's a bit confusing to me that there are two save buttons, one is called `saveButton` and one `cancelButton` and the PR is about adding a `done` button which can be cancel or save depending on some criteria?

2023-09-13 08:50 UTC, maikz commented on Sources/WishKit/Configuration/Config+Buttons.swift
> +        public var cancelButton = SaveButton()
I assume the name `SaveButton` only describes the Look and not the behavior of the button?

2023-09-13 08:50 UTC, maikz commented on Sources/WishKit/SwiftUI/WKButton.swift
> +        let button = style == .primary ? WishKit.config.buttons.saveButton : WishKit.config.buttons.cancelButton
If the style is primary it's a save button otherwise a cancel button? That needs at least a comment

2023-09-13 08:50 UTC, maikz commented on Sources/WishKit/Configuration/Config+Buttons.swift
> +        public var cancelButton = SaveButton()
Can't you reuse the saveButton for purposes of the cancelButton?

2023-09-15 06:34 UTC, frankschlegel requested changes

2023-09-15 06:34 UTC, frankschlegel commented on Sources/WishKit/SwiftUI/WKButton.swift
> +            return PrivateTheme.systemBackgroundColor.dark
Doesn't this affect all buttons now? I thought you only wanted to change the Save button style.

2023-10-05 09:30 UTC, closed without merging